spring:
  application:
    name: roshambo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/roshambo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: "user"
      password: "pass"
jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  refresh-token-key: ${REFRESH_TOKEN_KEY}
  refresh-token-ttl: 1d
  access-token-ttl: 15m
